### ISSUE TITLE
PopUpBox Background Bug

### ISSUE THREAD

**Issue by EmelieBrobergs** [ViktorNy/TheHousehold#100]
The dark background doesn't cover  whole screen on Emelis phone (Huawei P30) but do it on Nild phone.
![image](https://user-images.githubusercontent.com/70944598/140060434-4a7a981a-ed68-4cb6-a46b-0bb635677e01.png)
Nils phone

![image](https://user-images.githubusercontent.com/70944598/140060882-21b0ec71-c23a-46c5-a6d2-7e478abc6df5.png)
Emelie phone

**Comment by ViktorNy** [comment]
Note: Same problem on my phone Samsung Galaxy s20 FE
